Cypher/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Homepage.urls')),
    path('homepage/', include('Homepage.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Homepage/urls.py
from django.urls import path 
from . import views

app_name='homepage'

urlpatterns = [
    path('', views.index , name="index" ),
    path('facecheck/', views.FaceCheck , name="faceCheck"),
    path('drive/', views.drive, name="drive"),
    path('upload/', views.upload, name="upload"),
    path('open/<id>/',views.openfile,name='open'),
]

Homepage/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    User_ID= models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key=True)
    Auth_Image =models.CharField(max_length=15)
    key =models.CharField(max_length=100)

Homepage/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

Homepage/views.py
from django.shortcuts import render,HttpResponse,HttpResponseRedirect
from Homepage.models import UserProfile
from django.conf import settings
import face_recognition
import cv2
from cryptography.fernet import Fernet
from django.core.files.storage import FileSystemStorage
# Imaginary function to handle an uploaded file.

#Drive 
from allauth.socialaccount.models import SocialAccount, SocialApp
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
from googleapiclient.http import MediaFileUpload
from allauth.socialaccount.models import SocialToken, SocialApp
from googleapiclient.errors import HttpError
from googleapiclient.http import MediaIoBaseDownload
import io
import os
import docx2txt
stck=""
# Create your views here.
def index(request):
    return render(request, "index.html")

def FaceCheck(request):
    if request.method == 'GET':
            if(UserProfile.objects.filter(User_ID=request.user).exists()):
                User_Real_Face = face_recognition.load_image_file(f"media\{request.user.id}_{request.user}.jpg")
                User_Real_Face_encoding = face_recognition.face_encodings(User_Real_Face)[0]
                cam = cv2.VideoCapture(0)
                s, img = cam.read()
                if s:    # frame captured without any errors
                        cv2.imwrite("media/test.jpg",img)
                        Check_User_Face = face_recognition.load_image_file("media/test.jpg")
                        try:
                            face_recognition.face_encodings(Check_User_Face)[0]
                        except:
                            FaceCheck(request)
                        small_frame = cv2.resize(img, (0, 0), fx=0.25, fy=0.25)
                        # Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
                        rgb_small_frame = small_frame[:, :, ::-1]
                        # Find all the faces and face encodings in the current frame of video
                        face_locations = face_recognition.face_locations(rgb_small_frame)
                        face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations) 
                        try:                   
                            check=face_recognition.compare_faces(User_Real_Face_encoding, face_encodings)
                            if check[0]==True:
                                return HttpResponseRedirect('/homepage/drive/')
                            else:
                                return render(request, "unauthorized.html")   
                        except:
                             return render(request, "unauthorized.html") 
                else:
                    FaceCheck(request) 
            else:
                cam = cv2.VideoCapture(0)
                s, img = cam.read()              
                if s:    # frame captured without any errors 
                        cv2.imwrite(f"media\{request.user.id}_{request.user}.jpg",img)
                        User_Real_Face = face_recognition.load_image_file(f"media\{request.user.id}_{request.user}.jpg")
                        try:
                            User_Real_Face_encoding = face_recognition.face_encodings(User_Real_Face)[0]
                        except:
                            FaceCheck(request)  
                        obj = UserProfile()
                        obj.User_ID=request.user
                        key = Fernet.generate_key().decode()
                        obj.key=key
                        obj.Auth_Image= f"media\{request.user.id}_{request.user}.jpg"
                        obj.save()
                        return HttpResponseRedirect('/homepage/drive/')
                else:
                    return render(request, "unauthorized.html")   
                
                
def drive(request):
    app_google = SocialApp.objects.get(provider="google")
    account = SocialAccount.objects.get(user=request.user)
    user_tokens = account.socialtoken_set.first()
    
    creds = Credentials(
    token=user_tokens.token,
    refresh_token=user_tokens.token_secret,
    client_id=app_google.client_id,
    client_secret=app_google.secret,
    )
    try:
        service = build('drive', 'v3', credentials=creds)
        results = service.files().list(
            pageSize=10, fields="nextPageToken, files(id, name)").execute()
        items = results.get('files', [])
        flag=0
        if not items:
            print('No files found.')
        for i in items:
            if 'Cypher' in i.values():
                flag=1
        if (flag==0):
            file_metadata ={
                'name' : "Cypher",
                'mimeType' : "application/vnd.google-apps.folder",
            }
            service.files().create(body=file_metadata).execute()
            return HttpResponseRedirect('/homepage/drive/')    
    
        results = service.files().list(
            pageSize=10, fields="nextPageToken, files(id, name)").execute()
        items = results.get('files', [])
        if items:
            folder_id=""
            for item in items:
                if item['name']=="Cypher":
                    folder_id=item['id']
            page_token = None
            response = service.files().list(q=f"parents in '{folder_id}'",
                                                spaces='drive',
                                                fields='nextPageToken, files(id, name)',
                                                pageToken=page_token).execute()
            flist= response.get('files', [])
            if flist:
                folder_name=[]
                folder_ids=[]
                for item in flist:
                        folder_name.append(item['name'])
                        folder_ids.append(item['id'])
                        page_token = response.get('nextPageToken', None) 
                        
                mylist = zip(folder_name, folder_ids)
                context ={
                    "object_list": mylist,
                    }   
                return render(request, "check.html",context)       
    except HttpError as error:
        print(f'An error occurred: {error}')
        
    return render(request, "check.html")

def upload(request):
    if request.method == 'POST':
        app_google = SocialApp.objects.get(provider="google")
        account = SocialAccount.objects.get(user=request.user)
        user_tokens = account.socialtoken_set.first()
        creds = Credentials(
        token=user_tokens.token,
        refresh_token=user_tokens.token_secret,
        client_id=app_google.client_id,
        client_secret=app_google.secret,
        )
        service = build('drive', 'v3', credentials=creds) 
        
        results = service.files().list(
            pageSize=10, fields="nextPageToken, files(id, name)").execute()
        items = results.get('files', [])
        folder_id=""
        for item in items:
            if item['name']=="Cypher":
                folder_id=item['id']
                
                
        fname=request.FILES['file']
        fs = FileSystemStorage()
        filename = fs.save(fname.name, fname)
        uploaded_file_path = fs.path(filename)
        tname= fname.name
        Object=UserProfile.objects.get(User_ID=request.user)
        ftool = Fernet(Object.key)
        
        data=''
        with open(uploaded_file_path,'rb') as reader:
            data=reader.read()
        print(data)
        
        encryptedData=ftool.encrypt(data)
        
        with open(uploaded_file_path,'wb') as writer:
            writer.write(encryptedData)
            writer.close()
    
        file_metadata={
            'name': tname,
            'parents' : [folder_id],
        }
        mime_Type='application/vnd.openxmlformats-officedocument.wordprocessingml.document'
        media = MediaFileUpload(uploaded_file_path,mimetype=mime_Type)
        
        service.files().create(
            body=file_metadata,
            media_body=media,
        ).execute() 
    
        
        return HttpResponseRedirect('/homepage/drive/')    
    return render(request, "upload.html")


def openfile(request,id):
    if request.method == 'GET':
        app_google = SocialApp.objects.get(provider="google")
        account = SocialAccount.objects.get(user=request.user)
        user_tokens = account.socialtoken_set.first()
        creds = Credentials(
        token=user_tokens.token,
        refresh_token=user_tokens.token_secret,
        client_id=app_google.client_id,
        client_secret=app_google.secret,
        )
        service = build('drive', 'v3', credentials=creds) 
        file_id = id

        # pylint: disable=maybe-no-member
        request1 = service.files().get_media(fileId=file_id)
        dfile = io.BytesIO()
        downloader = MediaIoBaseDownload(dfile, request1)
        done = False
        while done is False:
            status, done = downloader.next_chunk()
            print(F'Download {int(status.progress() * 100)}.')
        fs = FileSystemStorage()
        filename = fs.save("test.docx", dfile)
        downloaded_file_path = fs.path(filename)
        Object=UserProfile.objects.get(User_ID=account.user_id)
        ftool = Fernet(Object.key)
        
        with open(downloaded_file_path,'rb') as reader1:
            data1=reader1.read()
        
        decryptedData=ftool.decrypt(data1)
        
        with open(downloaded_file_path,'wb') as writer1:
            writer1.write(decryptedData)
            
        my_text = docx2txt.process(downloaded_file_path)
        
        text=my_text.splitlines()
        context ={
            "object_list": text,
            }  
        
        if os.path.exists(downloaded_file_path):
            os.remove(downloaded_file_path)
        
        return render(request, "open.html", context) 
        
        

Homepage/templates/check.html
<!DOCTYPE html>
{% load socialaccount %}

<head>
    <script src="https://kit.fontawesome.com/047792a8a8.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
    .topright {
        position: absolute;
        right: 15px;
        top: 65px;
      }     
    .btn-primary {
        background-color: #36454F;
        border-color: #36454F
    }
    </style>
</head>

<body>
    <nav class="navbar fixed-top navbar-dark bg-dark" style="background-color: #36454F;">
        <span class="navbar-brand mb-0 h1" style="padding-left: 20px;"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-unlock" viewBox="0 0 16 16">
            <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2zM3 8a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H3z"/>
          </svg> Authorized Access 
            <span style="float: center;">    
                {% if user.is_authenticated %}
                    <a href="{% url 'account_logout' %}"> <button type="button" class="btn btn-primary" style=" border-radius: 10px; position: absolute; right: 10px; top: 6px; " ><i class="fa-brands fa-google"></i> Log Out</button></a>
                {% endif %} 
            <span> 
        </span>
    </nav>
    <br> <br> 
    <div class="card-header">
        <ol class="breadcrumb" style= " padding-left: 15px; padding-top: 15px">
            <li class="breadcrumb-item">Drive</li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'homepage:drive' %}">Cypher</a></li>
        </ol>
    </div>
    <div class="topright">
        <a href="{% url 'homepage:upload' %}"> <button type="button" class="btn btn-success" style=" border-radius: 10px;">Upload</button>  
    </div>
    <br>
    {% if object_list %}
    {% for obj in object_list %}
    <div class="card border-secondary text-center " style="width: 13rem; background-color: #f1f1f1; border-radius: 5px;float:left; margin-left: 25px;margin-bottom: 20px;">
        <div class="card-body">
            <h5 class="card-header text-white" style="font-weight: bold; border-radius: 0px; background-color: #393D47; margin-left: -21px; margin-right: -21px; margin-top: -21px;">{{obj}}</h5><br>
                <br>
                <button type="button" class="btn btn-dark pull-center" style="border-radius: 10px;"> Open <i class="fa-solid fa-arrow-right-to-bracket"></i></button>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    

</body>

</html>

Homepage/templates/index.html
<!DOCTYPE html>
{% load socialaccount %}

<head>
    <title>Login</title>
    <script src="https://kit.fontawesome.com/047792a8a8.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
     .login{
        position: fixed;
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
     }
     .bg-image{
        background-image: url('https://i.postimg.cc/fTFyMyyh/2785178.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        height: 100vh;
        ;
     }
            
    </style>

</head>

<body>
    <div class="bg-image">

    </div>
    
    <nav class="navbar fixed-top navbar-dark bg-dark" style="background-color: #36454F;">
        <span class="navbar-brand mb-0 h1" style="padding-left: 20px;"> <svg xmlns="http://www.w3.org/2000/svg" width="18" height="20" fill="currentColor" class="bi bi-shield-lock-fill" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M8 0c-.69 0-1.843.265-2.928.56-1.11.3-2.229.655-2.887.87a1.54 1.54 0 0 0-1.044 1.262c-.596 4.477.787 7.795 2.465 9.99a11.777 11.777 0 0 0 2.517 2.453c.386.273.744.482 1.048.625.28.132.581.24.829.24s.548-.108.829-.24a7.159 7.159 0 0 0 1.048-.625 11.775 11.775 0 0 0 2.517-2.453c1.678-2.195 3.061-5.513 2.465-9.99a1.541 1.541 0 0 0-1.044-1.263 62.467 62.467 0 0 0-2.887-.87C9.843.266 8.69 0 8 0zm0 5a1.5 1.5 0 0 1 .5 2.915l.385 1.99a.5.5 0 0 1-.491.595h-.788a.5.5 0 0 1-.49-.595l.384-1.99A1.5 1.5 0 0 1 8 5z"/>
          </svg> Cypher </span>
    </nav>
      
    
    {% if user.is_authenticated %}
    <div class="login">
        <meta http-equiv="REFRESH" content="0;url=http://127.0.0.1:8000/homepage/facecheck">
    </div>
    {% else %}
    <div class="login">

        <a href="{% provider_login_url "google" %}"> <button type="button" class="btn btn-primary" style="border-radius: 10px;" ><i class="fa-brands fa-google"></i> Sign in with Google</button></a>
        
    </div>

    {% endif %}


</body>

</html>

Homepage/templates/newuser.html
<!DOCTYPE html>
{% load socialaccount %}

<head>
    <title>Login</title>
    <script src="https://kit.fontawesome.com/047792a8a8.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
     .login{
        position: fixed;
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
     }
     .bg-image{
        background-image: url('https://i.postimg.cc/fTFyMyyh/2785178.jpg');
        background-size: cover;
        background-repeat: no-repeat;
        height: 100vh;
        ;
     }
            
    </style>

</head>

<body>
    <div class="bg-image">

    </div>
    
    <nav class="navbar fixed-top navbar-dark bg-dark" style="background-color: #36454F;">
        <span class="navbar-brand mb-0 h1" style="padding-left: 20px;"> <i class="fa-solid fa-book-open-reader"></i>Welcome New User </span>
    </nav>
      
    
    {% if user.is_authenticated %}
    <div class="login">

        <a href="{% url 'account_logout' %}"> <button type="button" class="btn btn-primary" style="border-radius: 10px;" ><i class="fa-brands fa-google"></i> Log Out</button></a>
        
    </div>

    {% endif %}


</body>

</html>

Homepage/templates/open.html
<!DOCTYPE html>
<html>
<head>
    <script src="https://kit.fontawesome.com/047792a8a8.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
    .topright {
        position: absolute;
        right: 15px;
        top: 65px;
      }     
    .btn-primary {
        background-color: #36454F;
        border-color: #36454F
    }
    .body {
        border-style: groove;
        max-width: 960px;
        max-height: fit-content;
        margin: auto;
        scroll-behavior: smooth;
        background-color: #FFFFFF;
  
      }
    </style>
</head>
<nav class="navbar fixed-top navbar-dark bg-dark" style="background-color: #36454F;">
        <span class="navbar-brand mb-0 h1" style="padding-left: 20px;"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-unlock" viewBox="0 0 16 16">
            <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2zM3 8a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H3z"/>
          </svg> Authorized Access 
            <span style="float: center;">    
                {% if user.is_authenticated %}
                    <a href="{% url 'account_logout' %}"> <button type="button" class="btn btn-primary" style=" border-radius: 10px; position: absolute; right: 10px; top: 6px; " ><i class="fa-brands fa-google"></i> Log Out</button></a>
                {% endif %} 
            <span> 
        </span>
</nav>
<br> <br> 
<div class="card-header">
        <ol class="breadcrumb" style= " padding-left: 15px; padding-top: 15px">
            <li class="breadcrumb-item">Drive</li>
            <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'homepage:drive' %}">Cypher</a></li>
        </ol>
    </div>
    <br>
<div class="body">
    <div>
        {% if object_list %}
        {% for obj in object_list %}
        {{obj}}
        <br>
        {% endfor %}
        {% endif %}
    </div>
</div>
<br><br>

<body>
</html>
    

Homepage/templates/unauthorized.html
<!DOCTYPE html>
{% load socialaccount %}

<head>
    <title>Login</title>
    <script src="https://kit.fontawesome.com/047792a8a8.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .btn-primary {
            background-color: #36454F;
            border-color: #36454F
        }     
            
    </style>

</head>

<body>
    <nav class="navbar fixed-top navbar-dark bg-dark" style="background-color: #36454F;">
        <span class="navbar-brand mb-0 h1" style="padding-left: 20px;"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-unlock" viewBox="0 0 16 16">
            <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2zM3 8a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H3z"/>
          </svg>Unauthorized Access 
            <span style="float: center;">    
                {% if user.is_authenticated %}
                    <a href="{% url 'account_logout' %}"> <button type="button" class="btn btn-primary" style=" border-radius: 10px; position: absolute; right: 10px; top: 6px; " ><i class="fa-brands fa-google"></i> Log Out</button></a>
                {% endif %} <span> 
            </span>
    </nav>
    <br> <br>


</body>

</html>

Homepage/templates/upload.html
<!DOCTYPE html>
{% load socialaccount %}

<head>
    <title>Login</title>
    <script src="https://kit.fontawesome.com/047792a8a8.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        .btn-primary {
            background-color: #36454F;
            border-color: #36454F
        }     
            
    </style>

</head>

<body>
    <nav class="navbar fixed-top navbar-dark bg-dark" style="background-color: #36454F;">
        <span class="navbar-brand mb-0 h1" style="padding-left: 20px;"> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-unlock" viewBox="0 0 16 16">
            <path d="M11 1a2 2 0 0 0-2 2v4a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2h5V3a3 3 0 0 1 6 0v4a.5.5 0 0 1-1 0V3a2 2 0 0 0-2-2zM3 8a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V9a1 1 0 0 0-1-1H3z"/>
          </svg>Authorized Access 
            <span style="float: center;">    
                {% if user.is_authenticated %}
                    <a href="{% url 'account_logout' %}"> <button type="button" class="btn btn-primary" style=" border-radius: 10px; position: absolute; right: 10px; top: 6px; " ><i class="fa-brands fa-google"></i> Log Out</button></a>
                {% endif %} <span> 
            </span>
    </nav>
    <br> <br>
    <div class="card-header">
    <ol class="breadcrumb" style= " padding-left: 15px; padding-top: 15px">
        <li class="breadcrumb-item">Drive</li>
        <li class="breadcrumb-item " ><a href="{% url 'homepage:drive' %}">Cypher</a></li>
        <li class="breadcrumb-item active"aria-current="page"><a href="{% url 'homepage:upload' %}">Upload</a></li>
    </ol>
    </div>
    <br>
    <div>
        <form action="{% url 'homepage:upload' %}" enctype="multipart/form-data" method="post">
            {% csrf_token %}
        <div class="mb-3">
                <input class="form-control" type="file" name="file">
        </div>
        <input type="submit" value="UPLOAD">
        </form>
    </div>


</body>

</html>